# Generated by Django 3.2.13 on 2022-06-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.TextField()),
                ('room_id', models.TextField(unique=True)),
                ('now_time', models.FloatField(default=0)),
                ('is_play', models.BooleanField()),
            ],
            options={
                'db_table': 'music_room',
            },
        ),
        migrations.CreateModel(
            name='YTList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_id', models.TextField(unique=True)),
                ('list_name', models.TextField(blank=True)),
                ('edit_password', models.TextField()),
            ],
            options={
                'db_table': 'yt_list',
            },
        ),
    ]
