# Generated by Django 3.2.13 on 2022-06-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt_player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicroom',
            name='is_play',
            field=models.BooleanField(default=False),
        ),
    ]
